package constant

// 默认服务配置
const (
	DEFAULT_SERVER_IP   = "127.0.0.1"
	DEFAULT_SERVER_PORT = "3000"
	DEV_ENV_FILE        = "../.dev.env"
	PROD_ENV_FILE       = ".prod.env"

	SESSION_KEY = "Identifier"
)

// 环境变量
const (
	SERVER_MODE = "SERVER_MODE"
	SERVER_IP   = "SERVER_IP"
	SERVER_PORT = "SERVER_PORT"

	MYSQL_URL      = "MYSQL_URL"
	MYSQL_USERNAME = "MYSQL_USERNAME"
	MYSQL_PASSWORD = "MYSQL_PASSWORD"
	MYSQL_DATABASE = "MYSQL_DATABASE"

	REDIS_URL      = "REDIS_URL"
	REDIS_USERNAME = "REDIS_USERNAME"
	REDIS_PASSWORD = "REDIS_PASSWORD"
	REDIS_DATABASE = "REDIS_DATABASE"
)
